name: Build and Publish
on: [push]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: minor
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.6'
      - name: Get Latest Release Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - run: make build_all VERSION=${{ steps.get-latest-tag.outputs.tag }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/**
          file_glob: true
          tag: ${{ steps.get-latest-tag.outputs.tag }}
          overwrite: false
