name: Build and Publish
on: [push]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.6'
      - run: make build_all
      - uses: actions/upload-artifact@v3
        with:
          path: build/